### ISSUE TITLE
Question regarding handles used within the useDocument function

### ISSUE THREAD

**Issue by CallumHemsley** [pvh/needle#2]
I'm trying to understand and use the `useDocument` function within `/renderer/Hooks.ts` but I'm struggling to grasp exactly what's happening here.

```js
const repo = useHandle<D>(url, (handle) => {
    handle.subscribe((doc) => {
      setDoc(doc)
    })

    return () => {
      setDoc(null)
    }
  })
```

I have several questions/confirmations:

- I believe the handle here is a RepoFrontend, where the repo has been `.open(url)`. I can't find any documentation from automerge/hypermerge about what `.open` does. But from the code, it seems to filter the repo based on the url, which is a unique id for the content type instance?
- Within the code block attached, the handle then does `.subscribe`, which is the method that sends a message stream. This is stated on the hypermerge GitHub page. This is another assumption, am I correct here?
- Thirdly, if it is sending a message stream, what is making it send the message stream, and therefore setting the doc? Is it that if someone makes a change to this component, it automatically knows it's changed, so will perform a `.subscribe` function?

If this doesn't seem clear, please let me know. Thanks again for the great support already given.

**Comment by pvh** [comment]
I think you've got it! 

The handle is not a RepoFrontend but a DocFrontend (or actually, probably a DocHandle or something like that.)

The setDoc(null) is a cleanup function for when you dispose of the handle.

Do you have your editor set up to track the Typescript types for you? It might help quite a bit.

**Comment by CallumHemsley** [comment]
Thanks for the very fast response!

Is there any way to know what exactly caused the `.subscribe` method to fire off, therefore setting the doc? From printing out the doc that is set inside `subscribe`, it seems to be the text content. I'm trying to understand the startup sort of life cycle that happens.

Here's what I've found so far, please correct me if I'm wrong:

1.  Root.tsx in the renderer will create a `Content` component with the context of "root".
2.  This `Content` component then will create a `Workspace` component.
3.  The workspace will then have its own `Doc`, by doing `useDocument(hypermergeUrl)`. But when this is first done, the workspace will be equal to `null`.
4. The workspace Doc is then set once the handle notices a change to the Doc? 

At point number 4, I'm unsure what exactly is making the change, and that's what I'm trying to figure out. (Is it possible that it's related to the heartbeat stuff?)

p.s - I do have the typescript types set up so I can click them and go to their type definitions.

**Comment by CallumHemsley** [comment]
EDIT -

I've managed to get subscribe working on my local project, so I know what wasn't making the change now. The doc gets changed when `create` is called inside the workspace. This will create a `text` content within it, changing the doc, and therefore `subscribe` will update and the doc won't be null. Thanks again, I'll close this.
