### ISSUE TITLE
Issues loading a different hypermerge url

### ISSUE THREAD

**Issue by CallumHemsley** [pvh/needle#3]
Hello,

I'm currently trying to simplify the Omnibox components so that an Omnibox isn't required. 

More specifically, I'm trying to allow the user to simply type into a search box, and click a button that says "load" to load the new workspace from a different user.

After looking through the omnibox code, I found that the code for loading a new workspace is simply 
```js
navigate = (url) => {
    window.location = url;
    this.props.omniboxFinished();
  };
```

However, when trying this without the rest of the Omnibox code, it wouldn't load a new workspace. I then looked through the code more, seeing that the `refreshHandle` method is called on ComponentDidUpdate.I tried adding the code related to the handle to the component but to no avail.

I'm still a little stumped as to exactly what needs to happen in order for a user to load a workspace. My reasoning now is that:

- First the handle needs to be refreshed, changing the hypermerge url to the new hypermerge url pasted in by the user.
- Once the handle is refreshed, and watching the repo from the hypermerge url, then we can call `window.location = url`.

Is there an important step that I'm missing?

Thanks again for the support so far!

**Comment by pvh** [comment]
So the workspace is the absolute root document for a particular user. After everything passes through the Pachinko machine it winds up here: https://github.com/pvh/needle/blob/default/src/renderer/components/content-types/workspace/Workspace.tsx#L145

This causes the Root.tsx to re-render and then everything follows on from there. Does that help? You can just throw out the whole Omnibox and call `setWorkspaceUrl(newUrl)` on Workspace if that helps.

**Comment by pvh** [comment]
Also, happy to jump on a Zoom some time this week and talk things through. Just ping me on the Automerge Slack. I'll be around.

**Comment by CallumHemsley** [comment]
Just gave this a go and it worked perfectly! For some reason, I didn't seem to find the `props.openDoc()` function within the omnibox stuff. This simplifies things a lot for me.

I probably spent way too much time trying to figure this out before making this issue, so I really appreciate the fast response. 

Thanks again, Peter!

**Comment by pvh** [comment]
Spending that time probably had other benefits but I'm happy to help when I can. Feel free to hit me up a little earlier in the process next time or just inquire on Slack.
